server {
    listen 80;
    server_name localhost;

    # Serve static frontend files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Enable React Router to handle URLs without 404s
        try_files $uri $uri/ /index.html;
    }

}
